version: "3"

volumes:
    html:

networks:
    proxy-tier:

services:
    db:
        image: postgres:12.3
        restart: always
        volumes:
            - ./volumes/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-SECRET_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
            - POSTGRES_USER=${POSTGRES_USER:-nextcloud}

    app:
        image: nextcloud:stable-fpm
        restart: always
        volumes:
            - ./.docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./volumes/nextcloud:/var/www/html
        environment:
            - POSTGRES_DB=db
            - POSTGRES_HOST=${POSTGRES_HOST:-db}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-SECRET_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin}
            - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-mydomain.coop}
        depends_on:
            - db

    web:
        image: nginx:1.18
        restart: always
        volumes:
            - ./.docker/web/nginx.conf:/etc/nginx/nginx.conf
            - ./volumes/nextcloud:/var/www/html:ro
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST:-mydomain.coop}
            - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-mydomain.coop}
        depends_on:
            - app
        networks:
            - proxy-tier
            - default

    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - .docker/nginx-proxy/conf.d:/etc/nginx/conf.d
            - .docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./certs:/etc/nginx/certs:ro
        networks:
            - proxy-tier

    nginx-letsencrypt:
        container_name: nginx-letsencrypt
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - .docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./certs:/etc/nginx/certs
        networks:
            - proxy-tier
        depends_on:
            - nginx-proxy

    cron:
        image: nextcloud:stable-fpm-alpine
        restart: unless-stopped
        volumes:
            - ./.docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./volumes/nextcloud:/var/www/html
        entrypoint: /cron.sh
