version: "3.7"

volumes:
  html:
  tmp:

services:
  db:
    image: postgres:12.3
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-SECRET_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}

  app:
    build:
      context: ./.docker/app
      target: prod
    restart: always
    volumes:
      - ./.docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./volumes/nextcloud:/var/www/html
      - ./dsv:/tmp/dsv
      - ./signer:/tmp/signer
      - tmp:/tmp/cfssl:rw
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-SECRET_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-mydomain.coop}
    depends_on:
      - db

  web:
    image: nginx:1.18
    restart: always
    ports:
      - 443:443
    volumes:
      - ./.docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/web/conf.d/nextcloud.conf:/etc/nginx/conf.d/nextcloud.conf
      - ./volumes/nextcloud:/var/www/html:ro
      - ./certs/default.crt:/etc/nginx/certs/default.crt
      - ./certs/default.key:/etc/nginx/certs/default.key
    depends_on:
      - app

  cron:
    image: nextcloud:stable-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./.docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./volumes/nextcloud:/var/www/html
    entrypoint: /cron.sh

  cfssl:
    build:
      context: ./.docker/app
      target: cfssl
    working_dir: /home/cfssl
    command: /home/cfssl/entrypoint.sh
    volumes:
      - ./.docker/cfssl/entrypoint.sh:/home/cfssl/entrypoint.sh
      - ./volumes/cfssl:/home/cfssl
      - tmp:/tmp/cfssl:ro
