
name: Changelog Reminder
on: pull_request

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: '/CHANGELOG.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}